# Introduction to recommender systems

## In this lesson, we will learn to

* formulate the **Recommendation Systems Problem**;
* explain what a **Utility Matrix** is and understand its key components;
* construct a utility matrix from user rating data (**Rating-based Utility Matrix Construction**);
* implement basic techniques for handling missing values in a utility matrix (**Utility Matrix Completion**);
* understand the idea behind **Collaborative Filtering** and how it leverages historical user interactions;
* build a **Content-Based Filtering** model and see how this approach naturally evolves into **vector representations (Embeddings)**;
* distinguish between classical methods and modern **Deep Hybrid Systems**, including **Two-Tower** and **Neural Collaborative Filtering** architectures;
* understand the structure of a modern recommendation pipeline, including the **Retrieval** and **Ranking** stages;
* formulate **Rating Prediction** as a **Supervised Machine Learning** problem;
* analyze the ethical challenges of recommendation systems, including **bias** and **filter bubbles**.

## Introduction to Recommendation Systems and Motivation

### What is a Recommendation System?

A **recommendation system** suggests products, services, or content that a user is likely to be interested in or interact with.

**Example**

Suppose a user visits Amazon to buy a product. Amazon has information about this user's previous interactions, as well as data from millions of other users with similar preferences and purchasing behavior.

The central question is:

> **What should Amazon recommend to this user to maximize the likelihood of a positive interaction or purchase?**

Unlike many traditional machine learning tasks, there is often **no single correct answer**. There is no explicit label that tells us exactly which item should be recommended.

Instead, the goal is to **learn and understand user behavior** in order to predict which items the user is most likely to find relevant.

---

### Why should we care about Recommendation Systems?

Recommendation systems affect almost every aspect of our digital lives. Whether we realize it or not, they influence much of what we watch, listen to, read, buy, and even who we connect with.

Examples include:

* Music streaming (Spotify)
* Video platforms (YouTube)
* Movies and TV shows (Netflix)
* Online shopping (Amazon, Rozetka, Prom.ua)
* News feeds and social media
* Restaurant recommendations
* Dating applications
* Friend suggestions (Facebook)
* Professional networking (LinkedIn)

Recommendation systems are also a key driver behind the success of many technology companies, including Amazon, Netflix, TikTok, and Meta.

One of their most important roles is to **reduce information overload**.

Modern online platforms often contain millions of items. Without recommendation and ranking algorithms, users would have to manually browse enormous catalogs to find something relevant.

For example, imagine searching for a hair dryer on Rozetka without any personalized recommendations or relevance-based sorting. You might need to browse through thousands of products before finding one that matches your needs.

### What does a Recommendation System actually predict?

A recommendation system does not necessarily try to predict what a user will buy. More generally, it predicts the likelihood of a **user interaction** with an item.

Depending on the application, an interaction may be:

* a click,
* a purchase,
* a movie watch,
* a song play,
* a like or share,
* adding a product to a cart or wishlist.

The exact objective depends on the business. For example, YouTube may optimize for watch time, while Amazon may focus on purchases.

Recommendation systems learn from **historical user behavior**. Instead of asking:

> *"What is the single correct item to recommend?"*

they ask:

> *"Which items is this user most likely to interact with?"*

The goal is to rank available items and present the most relevant ones to the user.

## Limitations of Recommendation Systems

Despite their benefits, recommendation systems also have important limitations.

They often suggest items that are similar to those a user has previously interacted with or that are popular among similar users. While this can improve the user experience, it may also create a **filter bubble**.

A filter bubble reduces a user's exposure to diverse information and viewpoints. This can be particularly problematic in areas such as news consumption, scientific research, and political discussions, where considering multiple perspectives is important.

---

## Data and Main Approaches

### What data do we need to build a Recommendation System?

Recommendation systems can use several types of data:

* **User-item interactions**: purchases, ratings, clicks, likes, adding items to a wishlist, etc.
* **User features**: demographic information or other descriptive attributes.
* **Item features**: category, description, price, genre, and other characteristics.

In the simplest case, a recommendation system can be built using only **historical user-item interactions**, without any additional information about users or items.

## Main Approaches to Building Recommendation Systems

### 1. Collaborative Filtering

Collaborative Filtering is based on a simple idea:

> **Users with similar preferences tend to interact with similar items.**

This approach relies only on **historical user-item interactions** (ratings, clicks, purchases, views) and does not require explicit information about users or items.

The goal is to discover hidden patterns in these interactions and use them to generate recommendations.

There are two main variants of Collaborative Filtering.

---

### User-based Collaborative Filtering

![](https://i0.wp.com/spotintelligence.com/wp-content/uploads/2024/04/user-based-collaborative-filtering.jpg?fit=1200%2C675\&ssl=1)

**Idea:**

Find users with preferences similar to the target user and recommend the items they liked.

#### How it works

1. Compute similarity between users based on their interactions.
2. Find the most similar users.
3. Recommend items they have interacted with but the target user has not.

**Intuition:**

> If people with tastes similar to yours liked an item, you will probably like it too.

---

### Item-based Collaborative Filtering

![](https://i0.wp.com/spotintelligence.com/wp-content/uploads/2024/04/item-based-collaborative-filtering.jpg?resize=1024%2C576\&ssl=1)

**Idea:**

Instead of finding similar users, find items that are similar to those the user already likes.

#### How it works

1. Compute similarity between items based on user interactions.
2. Find items the user has already interacted with.
3. Recommend similar items.

**Intuition:**

> If you liked this product, movie, or course, you will probably like similar ones as well.

---

### What is the main difference?

#### User-based Collaborative Filtering

This approach compares a user with many other users.

As the number of users grows, computing and updating user similarities becomes increasingly expensive. In addition, user preferences often change over time, requiring frequent recalculation.

**Advantages:**

* Simple and intuitive
* Works well on smaller datasets

**Limitations:**

* Difficult to scale
* Computationally expensive for large platforms

---

#### Item-based Collaborative Filtering

This approach focuses on similarities between items instead of users.

The number of items is often smaller than the number of users, and item relationships tend to be more stable over time. As a result, item similarities can be precomputed and reused.

**Advantages:**

* Faster recommendation generation
* Better scalability
* More stable in production systems

---

Both approaches rely solely on **historical interaction data** and do not require explicit user or item features.

**Important**: In Item-based Collaborative Filtering, items are considered similar if they are frequently interacted with by the same users. No explicit item features (such as category or description) are required.

**Limitation:** Collaborative Filtering cannot easily recommend completely new users or completely new items because there is little or no interaction history available. This challenge is known as the cold start problem.

### 2. Content-Based Recommender Systems

Content-Based Recommendation Systems focus on the **properties of the items themselves** and the preferences of a particular user.

The main idea is simple:

> **Recommend items that are similar to those the user already liked.**

![](https://i0.wp.com/spotintelligence.com/wp-content/uploads/2023/11/content-based-recommendation-system-1024x576.webp?resize=1024%2C576\&ssl=1)

---

### How does it work?

The first step is to represent each item using its features.

Examples:

* **Movies:** genre, actors, director, description.
* **Products:** category, brand, price, technical specifications.
* **Articles:** keywords, topics, text content.

These features are then converted into a numerical representation that a machine learning model can process.

Depending on the type of content, different techniques can be used:

* **Text:** TF-IDF or text embeddings.
* **Images:** features extracted by computer vision models.
* **Structured data:** numerical or categorical features.

In modern recommendation systems, these representations are often learned automatically as **embeddings**.

---

### How are recommendations generated?

The system:

1. Builds a user profile from items the user has previously interacted with.
2. Finds items with similar content.
3. Recommends those items to the user.

Unlike Collaborative Filtering, this approach does not depend on the behavior of other users.

---

### Advantages and Limitations

**Advantages:**

* Handles the **cold start problem for new items**.
* Produces personalized recommendations.
* Does not require data from other users.

**Limitations:**

* May recommend only very similar content, reducing diversity.
* Cannot easily discover unexpected but relevant items based on community behavior.

| Collaborative Filtering               | Content-Based Filtering            |
| ------------------------------------- | ---------------------------------- |
| Learns from **user behavior**         | Learns from **item features**      |
| No item descriptions required         | Requires item features             |
| Can discover surprising relationships | Usually recommends similar content |
| Suffers from new-item cold start      | Handles new-item cold start well   |

### 3. Hybrid Recommendation Systems

Collaborative Filtering and Content-Based Filtering each have their own strengths and limitations.

* **Content-Based Filtering** works well for new items but may recommend only similar content.
* **Collaborative Filtering** can discover patterns from community behavior but requires sufficient interaction history.

For this reason, most modern recommendation systems use a **hybrid approach** that combines both methods.

A hybrid model can leverage:

* **user behavior** (Collaborative Filtering),
* **item features** (Content-Based Filtering).

This combination helps to:

* reduce the **cold start problem**,
* improve recommendation quality,
* produce more robust results across different scenarios.

---

### How do Hybrid Systems work?

Hybrid recommendations can be generated in several ways:

* combining the outputs of multiple models;
* using content features together with interaction data;
* enriching collaborative recommendations with content-based signals.

As a result, the system benefits from both **individual user preferences** and **collective behavior patterns**.

---

Today, most large-scale platforms use some form of **hybrid recommendation system**, combining multiple data sources and machine learning models to deliver better recommendations.

## Formulating the Recommendation Problem

Recommendation systems are typically built from **user-item interactions**.

We have two entities:

* **(N) users**
* **(M) items**

Users are the consumers, while items are the products or services being recommended.

Examples of items:

* Movies (Netflix)
* Books (Amazon)
* Songs (Spotify)
* Products (Rozetka)
* User profiles (Tinder)

---

### The Utility Matrix

The interactions between users and items are represented by a **Utility Matrix**.

Each element ($y_{ij}$) represents the interaction between user ($i$) and item ($j$).

Depending on the application, an interaction may correspond to:

* a rating,
* a click,
* a purchase,
* a view,
* or any other user action.

For example, the matrix below contains (N=5) users and (M=6) items.

![](https://takuti.github.io/Recommendation.jl/latest/assets/images/cf.png)

Rows represent users, columns represent items.

A recommendation system can therefore represent:

* users by the items they interact with,
* items by the users who interact with them.

---

### Why is the Utility Matrix Sparse?

In real-world applications, users interact with only a small fraction of all available items.

For example, an online store may offer thousands of products, but a typical customer purchases only a few of them.

As a result, most entries in the utility matrix are missing, making it a **highly sparse matrix**.

---

### What are we trying to predict?

The central goal of a recommendation system is to **estimate the missing values in the Utility Matrix**.

In other words, given the observed interactions, we want to predict which unseen items a user is likely to prefer.

This problem is often referred to as **matrix completion**.

Once the missing interactions or ratings are estimated, we can recommend the items with the highest predicted scores.

---

### How is this different from traditional Machine Learning?

In many supervised learning problems:

* we have a feature matrix (X),
* and a target vector (y).

The objective is to predict the target variable.

In recommendation systems, the data is organized differently. Instead of predicting a single target column, we aim to predict the **missing entries of the Utility Matrix (Y)**.

This unique structure is one of the main characteristics of recommendation systems.

**Key Idea**: Recommendation systems are often viewed as a matrix completion problem—we observe only a small fraction of user-item interactions and try to infer the missing ones.

### Creating a Utility Matrix

Before building a recommendation model, we first need to organize user-item interactions into a suitable format.

In this example, we will work with a small toy dataset of movie ratings.

In [1]:
import os
import random
import sys
import time

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.decomposition import PCA
from sklearn.model_selection import cross_validate, train_test_split
from sklearn.preprocessing import StandardScaler

We start by loading the ratings data:

In [2]:
toy_ratings = pd.read_csv("data/toy_ratings.csv")
toy_ratings

   user_id            movie_id  rating
0      Sam           Lion King       4
1      Sam       Jerry Maguire       4
2      Sam      Roman Holidays       5
3      Sam            Downfall       1
4      Eva             Titanic       2
5      Eva       Jerry Maguire       1
6      Eva           Inception       4
7      Eva         Man on Wire       5
8      Eva  The Social Dilemma       5
9      Pat             Titanic       3
10     Pat           Lion King       4
11     Pat               Bambi       4
12     Pat           Cast Away       3
13     Pat       Jerry Maguire       5
14     Pat            Downfall       2
15     Pat    A Beautiful Mind       3
16     Jim             Titanic       2
17     Jim           Lion King       3
18     Jim  The Social Dilemma       5
19     Jim           Malcolm x       4
20     Jim         Man on Wire       5

The dataset contains three columns:

* `user_id`: the user who provided the rating;
* `movie_id`: the movie being rated;
* `rating`: the score given by the user.

Each row represents one observed user-item interaction.

At this point, the data is stored in a **long format**, where every row corresponds to a single rating.

Later, we will transform this table into a **utility matrix**, where:

* rows represent users,
* columns represent movies,
* values represent ratings.

#### Basic Dataset Statistics

Before constructing the utility matrix, it is useful to understand the size and sparsity of the dataset.

In [3]:
def get_stats(ratings, item_key="movie_id", user_key="user_id"):
    """
    Basic information about the dataset.
    """
    n_ratings = len(ratings)
    avg_rating = np.mean(ratings["rating"])

    N = ratings[user_key].nunique()
    M = ratings[item_key].nunique()

    density = n_ratings / (N * M)

    print(f"Number of ratings: {n_ratings}")
    print(f"Average rating: {avg_rating:.3f}")
    print(f"Number of users (N): {N}")
    print(f"Number of items (M): {M}")
    print(f"Fraction of observed ratings: {density:.3f}")

    return N, M


N, M = get_stats(toy_ratings)

Number of ratings: 21
Average rating: 3.524
Number of users (N): 4
Number of items (M): 12
Fraction of observed ratings: 0.438

The last metric, **Fraction of observed ratings**, measures how many entries in the utility matrix are known.

A low value indicates that the matrix is **sparse**, which is a common characteristic of recommendation systems.

---

#### Constructing the Utility Matrix

We can now transform the interaction table into a user-item matrix.

In [4]:
def get_user_item_matrix(ratings):
    return ratings.pivot(
        index="user_id",
        columns="movie_id",
        values="rating"
    )

# User-item matrix
user_item_matrix = get_user_item_matrix(toy_ratings)
user_item_matrix

movie_id,A Beautiful Mind,Bambi,Cast Away,Downfall,Inception,Jerry Maguire,Lion King,Malcolm x,Man on Wire,Roman Holidays,The Social Dilemma,Titanic
user_id,,,,,,,,,,,,
Eva,NaN,NaN,NaN,NaN,4.0,1.0,NaN,NaN,5.0,NaN,5.0,2.0
Jim,NaN,NaN,NaN,NaN,NaN,NaN,3.0,4.0,5.0,NaN,5.0,2.0
Pat,3.0,4.0,3.0,2.0,NaN,5.0,4.0,NaN,NaN,NaN,NaN,3.0
Sam,NaN,NaN,NaN,1.0,NaN,4.0,4.0,NaN,NaN,5.0,NaN,NaN

In this matrix:

* rows represent **users**;
* columns represent **items** (movies in our example);
* each cell contains the rating given by a user to a movie;
* missing values correspond to interactions that have not been observed.

Each user can be represented by the ratings they gave to movies, and each movie can be represented by the ratings it received from users.

> **Our goal is to estimate the missing values in this Utility Matrix.**

---

For convenience, we also create mappings between user and movie names and their corresponding matrix indices.

In [5]:
# Pandas Index objects containing user and item labels
users = user_item_matrix.index
items = user_item_matrix.columns

In [6]:
users

Index(['Eva', 'Jim', 'Pat', 'Sam'], dtype='object', name='user_id')

### Evaluating Recommendation Quality

In the following sections, we will experiment with different methods for filling the missing values in the Utility Matrix—that is, predicting unknown ratings.

There is no such thing as a "perfect" recommendation. However, we need a systematic way to evaluate and compare different approaches.

The basic idea is simple:

1. Hide a portion of the known ratings (**train/test split**).
2. Build the recommendation method using the remaining data.
3. Predict the hidden ratings.
4. Compare the predicted values with the actual ratings.

This process provides an objective measure of recommendation quality and allows us to compare different methods under the same conditions.

In other words, we temporarily pretend that some known ratings are missing and test how well the system can recover them.

### Splitting the Data

* We split the **ratings data** into training and validation sets.
* It is more convenient to split the original ratings table than to split the Utility Matrix directly.
* The Utility Matrix will then be constructed separately for the training and validation data.
* Do not worry about `y`; it is required by the `train_test_split` interface, but we will not actually use it.

In [7]:
X_train, X_val = train_test_split(
    toy_ratings, test_size=0.2, random_state=42
)

X_train.shape, X_val.shape

((16, 3), (5, 3))

We now construct separate Utility Matrices for the training and validation sets.

In [8]:
train_mat = get_user_item_matrix(X_train)
train_mat = train_mat.reindex(index=users, columns=items)

val_mat = get_user_item_matrix(X_val)
val_mat = val_mat.reindex(index=users, columns=items)

The `reindex()` operation ensures that both matrices have the **same rows (users) and columns (items)**, even if some users or movies do not appear in a particular split.

We can verify that the matrices have identical dimensions:

In [9]:
train_mat.shape, val_mat.shape

((4, 12), (4, 12))

Display the training and validation matrices:

In [10]:
train_mat

movie_id,A Beautiful Mind,Bambi,Cast Away,Downfall,Inception,Jerry Maguire,Lion King,Malcolm x,Man on Wire,Roman Holidays,The Social Dilemma,Titanic
user_id,,,,,,,,,,,,
Eva,NaN,NaN,NaN,NaN,4.0,1.0,NaN,NaN,5.0,NaN,NaN,2.0
Jim,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5.0,NaN,5.0,2.0
Pat,NaN,4.0,3.0,2.0,NaN,5.0,4.0,NaN,NaN,NaN,NaN,3.0
Sam,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN

In [11]:
val_mat

movie_id,A Beautiful Mind,Bambi,Cast Away,Downfall,Inception,Jerry Maguire,Lion King,Malcolm x,Man on Wire,Roman Holidays,The Social Dilemma,Titanic
user_id,,,,,,,,,,,,
Eva,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN
Jim,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN
Pat,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sam,NaN,NaN,NaN,NaN,NaN,4.0,4.0,NaN,NaN,NaN,NaN,NaN

Finally, we can compute the fraction of observed ratings in each matrix:

In [12]:
(len(X_train) / (N * M))  # Fraction of observed ratings in the training set

0.3333333333333333

In [13]:
(len(X_val) / (N * M))    # Fraction of observed ratings in the validation set

0.10416666666666667

* `train_mat` contains only the ratings from the training set.
* `val_mat` contains only the ratings from the validation set.

During evaluation, we assume that the ratings in `val_mat` are unknown. We predict these missing values using the training data and then compare the predictions with the actual ratings in the validation set.

* Training matrix: contains the ratings available to the recommendation system.
* Validation matrix: contains the ratings that were intentionally hidden and will be used for evaluation.
* Same shape: ensures that every matrix position (user, item) refers to the same interaction in both matrices. This makes it possible to compare predicted ratings with the true ratings correctly.

### Evaluating Prediction Accuracy

Now that we have training and validation sets, we need a way to measure the quality of our predictions.

A simple approach is to compare the **predicted ratings** with the **actual ratings** in the validation set and compute the prediction error.

For rating prediction tasks, common evaluation metrics include:

* **MSE (Mean Squared Error)**
* **RMSE (Root Mean Squared Error)**
* **MAE (Mean Absolute Error)**

In this notebook, we will use **RMSE**.

RMSE measures the average difference between the predicted and the actual ratings. Lower values indicate more accurate predictions.

Next, we will implement a function to compute the RMSE between two Utility Matrices.

In [14]:
def error(X_true, X_pred):
    """
    Returns the Root Mean Squared Error (RMSE)
    between the predicted and actual ratings.
    """
    return np.sqrt(np.nanmean((X_true - X_pred) ** 2))
    # Ignore missing ratings (NaN) when computing RMSE


def evaluate(pred_X, train_X, valid_X, model_name="Global average"):
    print("%s train RMSE: %0.2f" % (model_name, error(pred_X, train_X)))
    print("%s valid RMSE: %0.2f" % (model_name, error(pred_X, valid_X)))

The `error()` function computes the **RMSE** between two Utility Matrices.

Notice that we use `np.nanmean()`, which ignores missing (`NaN`) values. This is important because the Utility Matrix is sparse, and we only want to evaluate the ratings that actually exist.

## Baseline Approaches

We begin with a few simple methods for predicting the missing values in the Utility Matrix.

These are not sophisticated recommendation models, but they provide useful **baselines** against which more advanced methods can be compared.

1. **Global Average**

   Predict every missing rating using the average of all observed ratings.

2. **User Average**

   Predict a user's missing ratings using the average of that user's existing ratings.

3. **Item Average**

   Predict a missing rating using the average rating of the corresponding item across all users.

4. **User-Item Average**

   Predict a rating as the average of the user's mean rating and the item's mean rating.

5. **[k-Nearest Neighbours (k-NN) Imputation](https://scikit-learn.org/stable/modules/generated/sklearn.impute.KNNImputer.html)**

   Predict missing ratings using information from the most similar users or items.

---

In this notebook, we will implement the **Global Average** and **k-NN Imputation** approaches.

> A good recommendation model should outperform these simple baselines.

### Global Average Baseline

Our simplest baseline is to predict every missing rating using the **global average rating**.

In other words, we compute the average of all observed ratings in the training set and use this single value as the prediction for every unknown entry in the Utility Matrix.

Although this approach is extremely simple, it provides a useful reference point. Any recommendation method should ideally achieve a lower prediction error than this baseline.

In [15]:
avg = np.nanmean(train_mat)  # Compute the global average rating
pred_avg = np.zeros(train_mat.shape) + avg  # Fill the matrix with the global average

pd.DataFrame(pred_avg, columns=items, index=users)

movie_id,A Beautiful Mind,Bambi,Cast Away,Downfall,Inception,Jerry Maguire,Lion King,Malcolm x,Man on Wire,Roman Holidays,The Social Dilemma,Titanic
user_id,,,,,,,,,,,,
Eva,3.4375,3.4375,3.4375,3.4375,3.4375,3.4375,3.4375,3.4375,3.4375,3.4375,3.4375,3.4375
Jim,3.4375,3.4375,3.4375,3.4375,3.4375,3.4375,3.4375,3.4375,3.4375,3.4375,3.4375,3.4375
Pat,3.4375,3.4375,3.4375,3.4375,3.4375,3.4375,3.4375,3.4375,3.4375,3.4375,3.4375,3.4375
Sam,3.4375,3.4375,3.4375,3.4375,3.4375,3.4375,3.4375,3.4375,3.4375,3.4375,3.4375,3.4375

In [16]:
evaluate(pred_avg, train_mat, val_mat, model_name="Global average")

Global average train RMSE: 1.41
Global average valid RMSE: 0.83

The training RMSE measures the prediction error on the ratings available during model construction, while the validation RMSE measures the error on the held-out ratings.

For our experiments, the **validation RMSE** is the more important metric because it reflects how well the method generalizes to unseen interactions.

Our goal is to develop recommendation methods that achieve a **lower validation RMSE** than this simple baseline.

> Note: On this small toy dataset, the validation RMSE happens to be lower than the training RMSE due to the random train/test split. In larger datasets, this difference is usually much smaller.

### [k-Nearest Neighbours (k-NN) Imputation](https://scikit-learn.org/stable/modules/generated/sklearn.impute.KNNImputer.html)

Another simple approach is to fill the missing values in the Utility Matrix using the **k-Nearest Neighbours (k-NN)** algorithm.

The main idea is straightforward:

> To predict a missing rating, look for the **k most similar users** and use their ratings to estimate the unknown value.

The algorithm works by:

1. computing the similarity (or distance) between users;
2. finding the **k nearest neighbours**;
3. predicting missing ratings from the neighbours' available ratings.

To measure similarity, distances are computed using the ratings that are available for both users.

Although `KNNImputer` is a general-purpose missing-value imputation algorithm, it can also be applied to Utility Matrices as a simple recommendation baseline.

apply k-NN imputation to the training Utility Matrix:

In [17]:
from sklearn.impute import KNNImputer

# Initialize the imputer with k=2 neighbours
imputer = KNNImputer(
    n_neighbors=2,
    keep_empty_features=True
)

# Impute missing values in the training matrix
train_mat_imp = imputer.fit_transform(train_mat)

pd.DataFrame(train_mat_imp, columns=items, index=users)

movie_id,A Beautiful Mind,Bambi,Cast Away,Downfall,Inception,Jerry Maguire,Lion King,Malcolm x,Man on Wire,Roman Holidays,The Social Dilemma,Titanic
user_id,,,,,,,,,,,,
Eva,0.0,4.0,3.0,2.0,4.0,1.0,4.0,4.0,5.0,5.0,5.0,2.0
Jim,0.0,4.0,3.0,2.0,4.0,3.0,4.0,4.0,5.0,5.0,5.0,2.0
Pat,0.0,4.0,3.0,2.0,4.0,5.0,4.0,4.0,5.0,5.0,5.0,3.0
Sam,0.0,4.0,3.0,1.0,4.0,5.0,4.0,4.0,5.0,5.0,5.0,3.0

evaluate the imputed matrix:

In [18]:
evaluate(
    train_mat_imp,
    train_mat,
    val_mat,
    model_name="KNN imputer"
)

KNN imputer train RMSE: 0.00
KNN imputer valid RMSE: 1.48

The training RMSE is **0.00** because `KNNImputer` does not modify the ratings that already exist in the training matrix—it only fills the missing values.

The validation RMSE is much higher because we are evaluating how well those estimated ratings match the unseen validation data.

In this example, the k-NN imputation approach performs worse than the simple Global Average baseline, illustrating that a more complex method does not always produce better recommendations.

We can now compare the Utility Matrix after k-NN imputation with the original matrix to get an intuitive sense of the predicted ratings.

In [19]:
pd.DataFrame(train_mat_imp).astype(int)

   0   1   2   3   4   5   6   7   8   9   10  11
0   0   4   3   2   4   1   4   4   5   5   5   2
1   0   4   3   2   4   3   4   4   5   5   5   2
2   0   4   3   2   4   5   4   4   5   5   5   3
3   0   4   3   1   4   5   4   4   5   5   5   3

In [20]:
pd.DataFrame(
    user_item_matrix.fillna(0).astype(int).to_numpy()
)

   0   1   2   3   4   5   6   7   8   9   10  11
0   0   0   0   0   4   1   0   0   5   0   5   2
1   0   0   0   0   0   0   3   4   5   0   5   2
2   3   4   3   2   0   5   4   0   0   0   0   3
3   0   0   0   1   0   4   4   0   0   5   0   0


For visualization purposes, the missing values in the original Utility Matrix are temporarily replaced with `0`.

By comparing the two matrices, we can see which entries were estimated by the k-NN imputer and how those predictions differ from the original observed ratings.

**Once the missing values have been estimated, we can rank the items by their predicted relevance and recommend the highest-ranked items to the user.**

# Matrix Factorization for Recommendation Systems

So far, we have explored simple Collaborative Filtering approaches that estimate missing ratings from similar users or items.

While these methods are intuitive, they often struggle with sparse data and large-scale recommendation problems.

A more powerful and widely used approach is **Matrix Factorization**.

---

### Core Idea

Instead of directly comparing users or items, we assume that there exist a set of **hidden (latent) factors** that explain user preferences and item characteristics.

For example, in a movie recommendation system, latent factors might implicitly capture concepts such as:

* preference for action movies,
* interest in romance,
* appreciation of classic films,
* preference for documentaries.

These factors are **not explicitly provided** in the data—they are learned automatically from user-item interactions.

Intuitively:

* each user is represented by a vector of latent preferences;
* each item is represented by a vector of latent characteristics;
* the predicted rating is determined by how well these vectors match.

![](https://miro.medium.com/v2/resize\:fit:1400/format\:webp/1*QuK-dyK7j8equezsRYZ9hQ.png)

![](https://miro.medium.com/1*5js-e2mRMKYim8UuAhIL2Q.png)

[Matrix Factorization](https://developers.google.com/machine-learning/recommendation/collaborative/matrix) allows recommendation systems to:

* work effectively with sparse Utility Matrices;
* capture hidden patterns in user behavior;
* generalize to unseen interactions;
* scale well to large datasets.

---

### Connection to Previous Topics

We have already encountered one form of [matrix factorization](https://developers.google.com/machine-learning/recommendation/collaborative/matrix): **Singular Value Decomposition (SVD)**, which is also the mathematical foundation of PCA.

In recommendation systems, similar ideas are used to learn compact latent representations of users and items.

---

### Implementation

For the practical examples in this notebook, we will use the **`cornac`** library, which is designed specifically for recommendation systems.

You may also encounter the older **[`surprise`](https://github.com/NicolasHug/Surprise)** library in [online tutorials](https://machinelearningmastery.com/building-a-recommender-system-from-scratch-with-matrix-factorization-in-python/). Although it was widely used in the past, it is no longer actively maintained and may not work well with modern versions of `numpy`, `pandas`, and `scikit-learn`.

If you are interested in implementing Matrix Factorization from scratch, you can also explore [educational tutorials](https://medium.com/@rebirth4vali/implementing-matrix-factorization-technique-for-recommender-systems-from-scratch-7828c9166d3c) that derive the algorithm step by step.

> The latent vectors learned by Matrix Factorization can be viewed as early forms of embeddings.

In [21]:
# !pip install cornac -q

In [22]:
import cornac
print(cornac.__version__)

/opt/miniconda3/envs/mlpeople7/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

2.5.0

### Matrix Factorization with `cornac`

We can now train a Matrix Factorization model using the `cornac` library.

In [23]:
import cornac
from cornac.data import Dataset
from cornac.eval_methods import RatioSplit
from cornac.models import MF
from cornac.metrics import RMSE

# Data as (user, item, rating) tuples
data = toy_ratings[
    ["user_id", "movie_id", "rating"]
].values.tolist()

eval_method = RatioSplit(
    data=data,
    test_size=0.2,
    seed=42,
    rating_threshold=0.0
)

model = MF(
    k=10,
    max_iter=50,
    learning_rate=0.01,
    lambda_reg=0.02,
    seed=42
)

cornac.Experiment(
    eval_method=eval_method,
    models=[model],
    metrics=[RMSE()],
    user_based=True
).run()

TEST:
...
   |   RMSE | Train (s) | Test (s)
-- + ------ + --------- + --------
MF | 1.0961 |    0.0191 |   0.0021

The Matrix Factorization model learns **latent representations** for users and items and uses them to estimate missing ratings.

After training, we can generate recommendations for a particular user.

In [24]:
user_item_matrix

movie_id,A Beautiful Mind,Bambi,Cast Away,Downfall,Inception,Jerry Maguire,Lion King,Malcolm x,Man on Wire,Roman Holidays,The Social Dilemma,Titanic
user_id,,,,,,,,,,,,
Eva,NaN,NaN,NaN,NaN,4.0,1.0,NaN,NaN,5.0,NaN,5.0,2.0
Jim,NaN,NaN,NaN,NaN,NaN,NaN,3.0,4.0,5.0,NaN,5.0,2.0
Pat,3.0,4.0,3.0,2.0,NaN,5.0,4.0,NaN,NaN,NaN,NaN,3.0
Sam,NaN,NaN,NaN,1.0,NaN,4.0,4.0,NaN,NaN,5.0,NaN,NaN

In [25]:
model.recommend("Eva")

['The Social Dilemma',
 'Roman Holidays',
 'Man on Wire',
 'Bambi',
 'Lion King',
 'Jerry Maguire',
 'A Beautiful Mind',
 'Cast Away',
 'Titanic',
 'Downfall']

The output is a ranked list of items that the model predicts will be most relevant for **Eva**.

These recommendations are based on the latent factors learned from historical user-item interactions rather than explicit item features.

In [26]:
toy_ratings[
    toy_ratings.user_id == "Eva"
]

  user_id            movie_id  rating
4     Eva             Titanic       2
5     Eva       Jerry Maguire       1
6     Eva           Inception       4
7     Eva         Man on Wire       5
8     Eva  The Social Dilemma       5

> Matrix Factorization can be viewed as learning user embeddings and item embeddings. The predicted rating is computed from the interaction between these vectors.

# Content-Based Filtering (Content-Based Recommendations)

### What if we have a new item or a new user?

A common challenge in recommendation systems is the **cold start problem**.

If a new item or a new user has little or no interaction history, Collaborative Filtering cannot reliably generate recommendations.

Content-Based Filtering helps address this problem because it can rely on the **characteristics of users and items**, rather than only on historical ratings.

For example:

* Netflix can describe movies by genre, actors, or director.
* Amazon can describe books by category or topic.
* Tinder can describe users by age, location, or interests.

If these features are available, they can be used to estimate user preferences even when interaction data is limited.

---

## Main Idea

In Content-Based Filtering, we assume that we have access to **item features and/or user features**.

The goal is to learn the relationship between these features and the ratings provided by users.

For example, if a user consistently gives high ratings to action movies, the model may learn that this user prefers the "action" feature.

We can therefore build a **user profile** that captures individual preferences.

---

## Content-Based Filtering as a Supervised Learning Problem

Unlike Collaborative Filtering, where we rely only on interaction patterns, Content-Based Filtering can be formulated as a **Supervised Learning** task.

The observed ratings become the target values, while the user and item features serve as the input variables.

A simple approach is to build a separate regression model for each user:

1. Use item features as the input.
2. Use the user's ratings as the target.
3. Train a regression model.
4. Predict ratings for unseen items.

After training these models, we can estimate the missing values in the Utility Matrix and recommend the items with the highest predicted ratings.

![](https://github.com/UBC-CS/cpsc330-2024W2/blob/main/lectures/img/content-based-filtering.png?raw=true)

In the next section, we will build such a system step by step using a simple example.

### Movie Features

Suppose that, in addition to user ratings, we also have descriptive information about each movie.

In this example, each movie is represented by its genres.

In [27]:
movie_feats_df = pd.read_csv(
    "data/toy_movie_feats.csv",
    index_col=0
)

movie_feats_df

                    Action  Romance  Drama  Comedy  Children  Documentary
A Beautiful Mind         0        1      1       0         0            0
Bambi                    0        0      1       0         1            0
Cast Away                0        1      1       0         0            0
Downfall                 0        0      0       0         0            1
Inception                1        0      1       0         0            0
Jerry Maguire            0        1      1       1         0            0
Lion King                0        0      1       0         1            0
Malcolm x                0        0      0       0         0            1
Man on Wire              0        0      0       0         0            1
Roman Holidays           0        1      1       1         0            0
The Social Dilemma       0        0      0       0         0            1
Titanic                  0        1      1       0         0            0

> Note: In real-world recommendation systems, item features can be much richer than simple genre labels. They may include text descriptions, images, metadata, or learned embeddings.

### How can we use these features to predict missing ratings?

By combining the movie features with the observed ratings, we can build a Content-Based recommendation system.

The overall process is:

1. **Build a user profile**

   Learn what types of movies each user prefers based on the movies they have already rated.

2. **Train a supervised learning model for each user**

   Use the movie features as the input variables and the user's ratings as the target values.

3. **Predict missing ratings**

   Apply the trained model to movies the user has not yet rated and estimate their ratings.

Once the missing ratings have been predicted, we can recommend the movies with the highest predicted scores.

* Input features (X)  -> Movie genres
* Target values (y)   -> User ratings
* Model               -> One regression model per user
* Prediction          -> Missing ratings

### Building a User Profile Intro

Consider the user **Pat**.

We do not have any explicit information about Pat, but we do know how she rated several movies.

In [28]:
user_item_matrix.loc["Pat"]

movie_id
A Beautiful Mind      3.0
Bambi                 4.0
Cast Away             3.0
Downfall              2.0
Inception             NaN
Jerry Maguire         5.0
Lion King             4.0
Malcolm x             NaN
Man on Wire           NaN
Roman Holidays        NaN
The Social Dilemma    NaN
Titanic               3.0
Name: Pat, dtype: float64

We also have descriptive features for each movie.

The key assumption of Content-Based Filtering is that a user's ratings are related to the characteristics of the items they interact with.

For example, if Pat gave a high rating to **Lion King**, the model may learn that she prefers movies with features similar to those of *Lion King*.

In [29]:
movie_feats_df.loc["Lion King"]

Action         0
Romance        0
Drama          1
Comedy         0
Children       1
Documentary    0
Name: Lion King, dtype: int64

By combining movie features with Pat's ratings, we can build a user profile that captures her preferences and use it to predict ratings for unseen movies.

> In other words, the model tries to learn which movie features contribute positively or negatively to Pat's ratings.

### Building User Profiles

For each user (i), we can construct a personal preference model.

The process is straightforward:

1. Collect all movies rated by user (i).
2. Build a supervised learning dataset:

   * Each row in **`X`** contains the features of a movie rated by the user.
   * Each value in **`y`** is the rating that the user gave to that movie.
3. Train a regression model using `X` and `y`.
4. Use the trained model to predict ratings for unseen movies.

In other words, each user gets their own machine learning model that learns their individual preferences.

---


#### Example: Building a Profile for Pat

First, we retrieve the movies that Pat has rated.

In [30]:
movies_rated_by_pat = toy_ratings[
    toy_ratings["user_id"] == "Pat"
][["movie_id", "rating"]]

movies_rated_by_pat

            movie_id  rating
9            Titanic       3
10         Lion King       4
11             Bambi       4
12         Cast Away       3
13     Jerry Maguire       5
14          Downfall       2
15  A Beautiful Mind       3

Next, we construct the feature matrix `X` and the target vector `y`.

In [31]:
pat_X = movie_feats_df.loc[
    movies_rated_by_pat.movie_id
]

pat_y = movies_rated_by_pat.set_index(
    "movie_id"
)["rating"]

display(pat_X, pat_y)

                  Action  Romance  Drama  Comedy  Children  Documentary
Titanic                0        1      1       0         0            0
Lion King              0        0      1       0         1            0
Bambi                  0        0      1       0         1            0
Cast Away              0        1      1       0         0            0
Jerry Maguire          0        1      1       1         0            0
Downfall               0        0      0       0         0            1
A Beautiful Mind       0        1      1       0         0            0

movie_id
Titanic             3
Lion King           4
Bambi               4
Cast Away           3
Jerry Maguire       5
Downfall            2
A Beautiful Mind    3
Name: rating, dtype: int64

Here:

* `pat_X` contains the movie features.
* `pat_y` contains Pat's ratings.

This is now a standard supervised learning dataset:

* **Input features (`X`)** → movie characteristics.
* **Target values (`y`)** → Pat's ratings.

### Creating Training Data for All Users

We can repeat the same process for every user.

For each user, we collect:

* the features of the movies they have rated (`X`);
* the corresponding ratings (`y`).

In [32]:
def get_user_profile(user_name):
    rated_movies = toy_ratings[
        toy_ratings["user_id"] == user_name
    ][["movie_id", "rating"]]

    df = movie_feats_df.loc[
        rated_movies.movie_id
    ]

    df["rating"] = rated_movies.set_index(
        "movie_id"
    )["rating"]

    return df

In [33]:
users

Index(['Eva', 'Jim', 'Pat', 'Sam'], dtype='object', name='user_id')

In [34]:
user_profiles = dict()

for user in users:
    user_profiles[user] = get_user_profile(user)

user_profiles['Eva']

,Action,Romance,Drama,Comedy,Children,Documentary,rating
Titanic,0,1,1,0,0,0,2
Jerry Maguire,0,1,1,1,0,0,1
Inception,1,0,1,0,0,0,4
Man on Wire,0,0,0,0,0,1,5
The Social Dilemma,0,0,0,0,0,1,5

The `user_profiles` dictionary now contains the training data for each user, which will later be used to train individual recommendation models.

shapes of `X` and `y` will be a bit different for different users:
* **Number of features (columns of `X`)** → the same (six genres).
* **Number of training examples (rows of `X`)** → different, because users rate different numbers of movies.
* **Length of `y`** → also different.

### Exploring User Profiles

Let's inspect a few user profiles.

In [35]:
user_profiles["Pat"].style.background_gradient()

Pat appears to give relatively high ratings to movies that contain the **Children** and **Comedy** features. On the other hand, movies with the **Romance** feature seem to receive lower ratings.

These are only preliminary observations based on a small number of examples. The regression model will later learn these patterns automatically.

---

In [36]:
user_profiles["Eva"].style.background_gradient()

Eva has rated only a few movies, so her profile contains much less information.

Based on the available data, it appears that she tends to give higher ratings to **Documentary** and **Action** movies, while **Romance** movies receive lower ratings.

Because the dataset is small, these observations should be interpreted with caution.

### A Supervised Learning Approach to Rating Prediction

Now that we have constructed `X` and `y` for each user, we can train a separate regression model for every user.

In [37]:
from sklearn.linear_model import Ridge

def train_user_model(user_name, model=Ridge()):
    """
    Train a model for a given user.
    """
    df = user_profiles[user_name]
    X = df.drop(columns="rating")
    y = df["rating"]
    model.fit(X, y)
    return model


def predict_user_model(
    model,
    movie_names,
    movie_feats_df=movie_feats_df
):
    """
    Predict movie ratings for a given user.
    """
    feat_vecs = movie_feats_df.loc[
        movie_names
    ].values

    preds = model.predict(feat_vecs)
    return preds

### Regression Model for Pat

We train a Ridge Regression model for Pat.

In [38]:
user_name = "Pat"
pat_model = train_user_model(user_name)

Since we are using a linear model, we can inspect the learned regression coefficients.

In [39]:
def get_coef_df(
    user_name,
    model,
    movie_feats_df=movie_feats_df
):
    coef_col_name = (
        f"Coefficients for {user_name}"
    )

    return pd.DataFrame(
        model.coef_,
        index=movie_feats_df.columns,
        columns=[coef_col_name]
    )


get_coef_df(user_name, pat_model)

             Coefficients for Pat
Action                   0.000000
Romance                 -0.020833
Drama                    0.437500
Comedy                   0.854167
Children                 0.458333
Documentary             -0.437500

The learned coefficients can be interpreted as a simple **user preference profile**.

* Positive coefficients indicate features that tend to increase Pat's predicted rating.
* Negative coefficients indicate features that tend to decrease it.
* Larger absolute values correspond to stronger preferences.

For example, this model suggests that Pat prefers **Comedy** and **Children** movies, while **Documentary** movies are less likely to receive high ratings.

---

### Predicting Ratings for New Movies

We can now estimate how Pat might rate movies she has not yet seen.

In [40]:
movies_to_pred = [
    "Roman Holidays",
    "Malcolm x"
]

pred_df = movie_feats_df.loc[
    movies_to_pred
]

preds = predict_user_model(
    pat_model,
    movies_to_pred,
    movie_feats_df
)

pred_df[
    f"{user_name}'s predicted ratings"
] = preds

pred_df

/opt/miniconda3/envs/mlpeople7/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

,Action,Romance,Drama,Comedy,Children,Documentary,Pat's predicted ratings
Roman Holidays,0,1,1,1,0,0,4.145833
Malcolm x,0,0,0,0,0,1,2.437500

According to the model, Pat is more likely to enjoy **Roman Holidays** than **Malcolm x**, based solely on the movie features and her previous ratings.

### Regression Model for Eva

We can repeat the same process for another user.

In [41]:
user_name = "Eva"

eva_model = train_user_model(user_name)

get_coef_df(user_name, eva_model)

             Coefficients for Eva
Action                   0.333333
Romance                 -1.000000
Drama                   -0.666667
Comedy                  -0.666667
Children                 0.000000
Documentary              0.666667

The learned coefficients represent Eva's estimated preferences.

Based on the available ratings, the model suggests that **Documentary** and **Action** features contribute positively, while **Romance** features contribute negatively.

Since Eva has rated only a few movies, these estimates are based on limited data and may not be very stable.

---

### Predicting Ratings for New Movies

We can now predict how Eva might rate the same unseen movies.

In [42]:
preds = predict_user_model(
    eva_model,
    movies_to_pred
)

pred_df[
    user_name + "'s predicted ratings"
] = preds

pred_df

/opt/miniconda3/envs/mlpeople7/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

,Action,Romance,Drama,Comedy,Children,Documentary,Pat's predicted ratings,Eva's predicted ratings
Roman Holidays,0,1,1,1,0,0,4.145833,1.666667
Malcolm x,0,0,0,0,0,1,2.437500,4.666667

According to the model, Eva is more likely to enjoy **Malcolm x** than **Roman Holidays**, based on the movie features and her previous ratings.

### Filling the Utility Matrix with Content-Based Filtering

Recall our original Utility Matrix.

In [43]:
user_item_matrix

movie_id,A Beautiful Mind,Bambi,Cast Away,Downfall,Inception,Jerry Maguire,Lion King,Malcolm x,Man on Wire,Roman Holidays,The Social Dilemma,Titanic
user_id,,,,,,,,,,,,
Eva,NaN,NaN,NaN,NaN,4.0,1.0,NaN,NaN,5.0,NaN,5.0,2.0
Jim,NaN,NaN,NaN,NaN,NaN,NaN,3.0,4.0,5.0,NaN,5.0,2.0
Pat,3.0,4.0,3.0,2.0,NaN,5.0,4.0,NaN,NaN,NaN,NaN,3.0
Sam,NaN,NaN,NaN,1.0,NaN,4.0,4.0,NaN,NaN,5.0,NaN,NaN

After training a separate regression model for each user, we can predict ratings for all movies and construct a completed Utility Matrix.

In [44]:
from sklearn.linear_model import Ridge

models = dict()
pred_lin_reg = []

for user in users:
    model = train_user_model(user)
    models[user] = model
    pred_lin_reg.append(
        predict_user_model(
            model,
            movie_names=items
        )
    )

pd.DataFrame(
    pred_lin_reg,
    columns=items,
    index=users
).astype(int)

/opt/miniconda3/envs/mlpeople7/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/opt/miniconda3/envs/mlpeople7/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/opt/miniconda3/envs/mlpeople7/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/opt/miniconda3/envs/mlpeople7/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

movie_id,A Beautiful Mind,Bambi,Cast Away,Downfall,Inception,Jerry Maguire,Lion King,Malcolm x,Man on Wire,Roman Holidays,The Social Dilemma,Titanic
user_id,,,,,,,,,,,,
Eva,2,3,2,4,3,1,3,4,4,1,4,2
Jim,2,3,2,4,3,2,3,4,4,2,4,2
Pat,3,3,3,2,3,4,3,2,2,4,2,3
Sam,3,3,3,1,3,4,3,1,1,4,1,3

The resulting matrix contains the predicted ratings generated by the Content-Based recommendation models.

---

It is interesting to compare these predictions with the original Utility Matrix.

In [45]:
user_item_matrix.fillna(0).astype(int).style.background_gradient()

(Remember that `0` is used here only to visualize missing values.)

We can see that the model generates reasonable estimates for previously unseen user-item interactions, effectively filling the missing entries of the Utility Matrix.

One interesting observation is that the predicted ratings rarely reach the extreme values of the rating scale.

Note: The model is not choosing among the discrete ratings {1, 2, 3, 4, 5}. Instead, it predicts continuous values, which are often concentrated around the average rating.

### Summary: Content-Based Recommendation Systems

Building a separate model for each user is one of the classical formulations of **Content-Based Filtering**.

In this approach, every user has an individual preference model, and recommendations are generated by finding items whose features best match that user's interests.

This approach is particularly useful when:

* **personalization** is important;
* users have relatively stable preferences;
* rich **item features** are available;
* recommendations should be **interpretable** (it is possible to explain why an item was recommended);
* recommendations should not depend on the behavior of other users.

Typical applications include:

* news and blog recommendations;
* article, course, and job recommendations;
* personalized content feeds;
* privacy-sensitive systems.

One of the main advantages of this approach is that it can recommend **new items**, even when they have no interaction history, as long as their features are known.

However, maintaining a separate model for every user can become computationally expensive as the number of users grows.

For this reason, modern large-scale recommendation systems often combine Content-Based Filtering with Collaborative Filtering and embedding-based methods.

> In this notebook, we used one regression model per user. Modern deep learning recommenders often replace these individual models with shared neural networks that learn user and item embeddings.

# Modern Recommendation Systems: Deep Hybrid Approaches

So far, we have studied the classical approaches to recommendation systems. They are extremely useful for understanding the underlying ideas, but modern production systems are usually much more sophisticated.

[Kaggle tutorial](https://www.kaggle.com/code/ibtesama/getting-started-with-a-movie-recommendation-system) worth to explore, which demonstrates a larger MovieLens dataset and uses TF-IDF vectorization for movie descriptions.

---


## Why do we need more advanced approaches?

Training a separate model for every user is difficult to maintain and does not scale well to millions of users.

Moreover, real-world systems often have access to many different sources of information:

* user behavior,
* user characteristics,
* item characteristics,
* interaction history,
* temporal information,
* text,
* images,
* audio,
* video.

Modern recommendation systems therefore combine both **Collaborative Filtering** and **Content-Based Filtering** into a unified architecture based on **Deep Learning**.

Although implementations differ across companies, most large-scale recommendation systems are built around three key ideas:

1. Learning **embeddings**.
2. **Retrieving** a small set of candidate items.
3. **Ranking** those candidates.

---


## 1. Embedding-based Recommendation (Vector Space Model)

A fundamental idea behind modern recommendation systems is to represent both users and items as vectors of the same dimensionality in a shared vector space.

```text
User  -> [0.2, -0.5, 0.8, ...]
Movie -> [0.3, -0.4, 0.7, ...]
              ↓
      cosine similarity
              ↓
        high similarity
          recommend!
```

You can think of embeddings as learned feature vectors.

They generalize:

* the latent factors learned by Matrix Factorization,
* the handcrafted features used in Content-Based Filtering.

---


### Step 1: Create Item Embeddings

Instead of manually defining features, neural networks can automatically generate dense vector representations.

Different data modalities use different models:

* **Text (title, description):**
  BERT, RoBERTa, E5, or modern LLM embeddings.

* **Images:**
  CNNs (ResNet) or Vision Transformers (ViT).

* **Audio:**
  Audio embedding models.

* **Categories or tags:**
  Simple Embedding layers.

If multiple information sources are available, they can be combined before generating the final embedding.

For example, a movie embedding may be built from:

* title,
* description,
* genres,
* actors,
* tags.

---


### Step 2: Create User Embeddings

Suppose we already have embeddings for all movies.

How do we create an embedding for a user?

The simplest and surprisingly effective approach is **Average Pooling**.

1. Collect the embeddings of all movies the user liked.
2. Compute their average.
3. Use this average vector as the user embedding.


```python
# Simple average
user_embedding = np.mean(
    [
        item_embeddings[item]
        for item in user_interactions
    ],
    axis=0
)
```

A more advanced approach is to assign different weights to different interactions.

For example:

* recent interactions may be more important;
* purchases may be more important than clicks.

```python
user_embedding = np.average(
    [
        item_embeddings[item]
        for item in user_interactions
    ],
    weights=[
        interaction_weights[item]
        for item in user_interactions
    ],
    axis=0
)
```

More advanced recommendation systems often replace simple averaging with attention mechanisms or Transformer architectures.

---


### Step 3: Find Similar Items

Suppose we have:

* one user embedding,
* millions of item embeddings.

The goal is to find the items closest to the user vector.

The most common similarity measure is:

#### Cosine Similarity

The closer the cosine similarity is to 1, the more similar the vectors are.

Conceptually, this is very similar to performing a k-Nearest Neighbours search in embedding space.

---

#### Approximate Nearest Neighbours (ANN)

Computing the distance between one user and millions of items can be computationally expensive.

Instead, production systems use specialized ANN algorithms that perform very fast approximate searches.

Popular libraries include:

* [FAISS (Meta)](https://github.com/facebookresearch/faiss)
* [Annoy (Spotify)](https://github.com/spotify/annoy)
* [ScaNN (Google)](https://github.com/google-research/google-research/tree/master/scann)

ANN methods can retrieve the top few hundred candidate items in just a few milliseconds.

References:
* [ANN explain]((https://medium.com/data-science-collective/understanding-annoy-the-approximate-nearest-neighbors-oh-yeah-by-spotify-636f875c04c4))
* [ANN explain video](https://www.youtube.com/watch?v=DRbjpuqOsjk)

---


## 2. Retrieval and Ranking Architecture

Modern recommendation systems rarely search and rank millions of items simultaneously.

Instead, they divide the problem into two stages.

```text
Millions of items
        ↓
    Retrieval
        ↓
 Hundreds of candidates
        ↓
      Ranking
        ↓
    Top recommendations
```

---


### Stage 1: Retrieval

#### Goal

Quickly eliminate obviously irrelevant items and keep only a small set of promising candidates.

For example:

```text
1,000,000 videos
        ↓
      500 candidates
```

#### Typical methods

* user embeddings,
* item embeddings,
* cosine similarity,
* ANN search.

#### Characteristics

* extremely fast,
* approximate,
* prioritizes recall over precision.

The main objective is:

> Do not miss good candidates.

---


### Stage 2: Ranking

#### Goal

Sort the candidate items and select the best few recommendations.

For example:

```text
500 candidates
      ↓
 Top 10 recommendations
```

#### Typical methods

* Gradient Boosting (XGBoost, CatBoost),
* Deep Neural Networks,
* hybrid models.

The ranking model can use many additional features:

* user history,
* item embeddings,
* time of day,
* device type,
* previous interactions,
* contextual information.

Unlike Retrieval, Ranking can afford to use much more complex models because it processes only a small number of candidates.

---


## Example: YouTube Recommendation System

A classic example of this architecture is presented in the paper:

**[Deep Neural Networks for YouTube Recommendations (2016)](https://static.googleusercontent.com/media/research.google.com/ru//pubs/archive/45530.pdf)**

The system operates in two stages.

![](https://cdn-images-1.medium.com/max/800/0*U5iR5NTSChuSOcyc.)

---

### Candidate Generation Network

The goal is to select a few hundred relevant videos from millions.

Typical input features include:

* embeddings of recently watched videos,
* embeddings of recent search queries,
* user demographics,
* geographical information,
* video age.

All features are concatenated and passed through a neural network.

The network produces a **user embedding**.

During training, the model learns to predict which video the user is likely to watch next.

As a result, both users and videos are represented as embeddings in the same vector space.

During inference:

```text
User embedding
        ↓
 ANN search
        ↓
Top candidate videos
```

![](https://cdn-images-1.medium.com/max/800/0*nimT6kgFmzV_0jPZ.)

---

### Ranking Network

The second stage receives the candidate videos and produces a final ranking.

Additional features may include:

* candidate video embedding,
* channel interaction history,
* contextual features,
* previous watch history,
* device information.

These features are processed by a larger neural network that predicts a ranking score.

![](https://cdn-images-1.medium.com/max/800/0*1958DpFdwS3fc-Cf.)

---

### Why not predict watch time directly?

Predicting exact watch time is difficult because:

* watch time is highly variable,
* the distribution is heavily skewed,
* different videos have different lengths,
* the data contains significant noise.

Instead, YouTube formulates the problem as a binary classification task.

The model predicts whether the user is likely to engage with the content.

To encourage longer viewing sessions, positive examples are weighted according to their watch time.

This combines:

* the stability of binary classification,
* optimization toward long-term user engagement.

---

### Important Ideas from the YouTube Paper

Many of the ideas introduced in this paper are useful beyond recommendation systems.

#### Example Age

Older videos naturally accumulate more views.

Including video age as a feature helps the model avoid unfairly favoring older content and improves recommendations for newly uploaded videos.

---

#### Asymmetric Co-watch

If a user watches video A and then video B, the training example is:

```text
A → B
```

but not

```text
B → A
```

The order matters because user behavior is sequential.

---

#### Negative Sampling

Instead of using only videos that were shown to the user, negative examples are sampled from the entire video corpus.

This teaches the model to answer:

> Why should this video be recommended instead of millions of alternatives?

---

#### Watch Time vs. Click-Through Rate

A high click-through rate does not necessarily imply a good user experience.

Clickbait titles and thumbnails may generate many clicks but very short viewing sessions.

Optimizing for watch time better aligns the recommendation system with long-term user satisfaction.

---

## 3. Concat-based Models

So far, we have represented users and items as separate embeddings and compared them using similarity measures such as cosine similarity.

But what if we simply combine all available information about the user and the item and let a machine learning model learn their interactions directly?

This is exactly the idea behind **Concat-based models**.

---


### Core Idea

We collect all available features for a user and an item, concatenate them into a single vector, and train a model to predict whether the user will interact with that item.

```text
User features  ┐
               ├── concat ──► Machine Learning Model ──► Score
Item features  ┘
```

Typical user features may include:

* age,
* gender,
* interaction history,
* location,
* device type.

Typical item features may include:

* category,
* price,
* textual description,
* image embedding,
* popularity.

The training data consists of positive and negative user-item pairs:

* Positive: the user interacted with the item.
* Negative: the user did not interact with the item.

---


### Neural Network Implementation

A common implementation uses a Multi-Layer Perceptron (MLP).

```python
user_features = [age, gender, history, ...]
item_features = [category, price, description, ...]

x = concat(
    user_features,
    item_features
)

score = MLP(x)
```

The network learns complex relationships between user and item features.

This is conceptually similar to the Ranking Network used in the YouTube recommendation architecture, where all features are combined early and processed jointly.

---


### Gradient Boosting Alternative

Neural networks are not strictly necessary.

The same concatenated feature vector can be used with models such as:

* XGBoost,
* LightGBM,
* CatBoost.

These methods often perform very well, especially when the amount of training data is moderate.

---

### Advantages

* **Captures complex interactions** between user and item features.
* **Easy to extend** — new features (time, device, location, context, etc.) can simply be added to the input vector.
* **Flexible** — works with both neural networks and models such as XGBoost or LightGBM.

---

### Limitations

* **Cannot be efficiently indexed** — user and item representations are mixed inside the model, so ANN search (FAISS, Annoy, etc.) cannot be used.
* **Computationally expensive** — every `(user, item)` pair must be evaluated.
* **Mainly used for Ranking** — in production systems, it is typically applied after a Retrieval stage has reduced millions of items to a few hundred candidates.

```text
Millions of items
        ↓
    Retrieval
        ↓
 Hundreds of candidates
        ↓
 Concat-based Model
        ↓
 Final Ranking
```

## 4. Two-Tower Architecture

The Two-Tower architecture is one of the most popular neural network architectures for modern recommendation systems.

Its main advantage is that it learns **user embeddings** and **item embeddings** independently, allowing item embeddings to be precomputed and stored for very fast Retrieval.

---


### Core Idea

Instead of building a user embedding by simply averaging item embeddings, we train two separate neural networks:

1. **User Tower**

   * Input: viewing history, demographics, location, etc.
   * Output: user embedding.

2. **Item Tower**

   * Input: description, image, price, category, etc.
   * Output: item embedding.

```text
User features ──► User Tower ──► User Embedding
                                             \
                                              dot product
                                             /
Item features ──► Item Tower ──► Item Embedding
```

During training, the model learns to make embeddings of positive user-item pairs close together and embeddings of unrelated pairs far apart.

![](https://redis.io/_next/image/?url=https%3A%2F%2Fcdn.sanity.io%2Fimages%2Fsy1jschh%2Fproduction%2Fbe5b5fa034b62eb79df8c582ec1ad50bbe3abcad-1254x680.jpg\&w=1200\&q=75\&dpl=dpl_J6kvpkLVT5JapL21tuWVmKzqemFd)

---


### Why not simply concatenate everything?

Both Concat-based models and Two-Tower models eventually combine information from users and items.

The difference is **when** this happens.

### Concat-based (Early Fusion)

```text
User features ─┐
               ├── concat ─► Neural Network
Item features ─┘
```

User and item information are mixed immediately.

---


### Two-Tower (Late Fusion)

```text
User features ─► User Tower ─► User Embedding
                                           \
                                            dot product
                                           /
Item features ─► Item Tower ─► Item Embedding
```

The model first learns independent representations and only combines them at the final stage.

Because item embeddings are independent of users, they can be precomputed and indexed with ANN libraries such as FAISS.

This makes Two-Tower models an excellent choice for the **Retrieval** stage.

---


## 5. Sequence-based Models (Transformers)

So far, we have mostly ignored the order of user interactions.

However, in many applications, **the sequence itself contains important information**.

For example:

* users often buy a phone before buying a phone case;
* users may watch an introductory course before an advanced one.

Sequence-based recommendation models explicitly model these temporal patterns.

---


### Core Idea

Given a sequence of previous interactions,

```text
[Item A, Item B, Item C] → ?
```

predict the next item the user is likely to interact with.

---

### Architecture

Modern recommendation systems typically use:

* Transformers,
* occasionally RNNs or LSTMs (less common today).

These models are very similar to the Transformer architectures used in modern language models.

Instead of predicting the next word, they predict the next item.

Typical applications include:

* TikTok,
* Spotify,
* YouTube,
* session-based recommendation systems.

---

## Summary Table

| Method                 | Main Idea                     | Best Use Case        |
| ---------------------- | ----------------------------- | -------------------- |
| **Embeddings**         | Vector similarity             | Similar items        |
| **Two-Tower**          | Separate user/item embeddings | Fast Retrieval       |
| **Concat-based (MLP)** | Early feature fusion          | Ranking              |
| **Transformer**        | Sequential modeling           | Next-item prediction |

---

## Which Approach Should You Choose?

* **Small projects / Proof of Concept**

  * simple embeddings,
  * per-user models.

* **Medium-scale systems**

  * Concat-based models,
  * user and item features.

* **Large production platforms**

  * Two-stage architecture,
  * Two-Tower Retrieval,
  * Ranking model,
  * Sequence models,
  * Hybrid approaches.

## Summary

We have explored several families of recommendation systems.

### Classical Approaches

```text
Content-Based Filtering
    ↓
One regression model per user

Collaborative Filtering
    ↓
Matrix Factorization
```

These methods are excellent for understanding the fundamental ideas behind recommendation systems.

---

### Modern Deep Hybrid Systems

Modern production systems typically combine multiple approaches:

```text
User & Item Features
          ↓
     Embeddings
          ↓
      Retrieval
    (Two-Tower)
          ↓
       Ranking
   (Concat-based MLP)
          ↓
 Sequence Modeling
   (Transformers)
```

The key idea is that modern recommendation systems combine the strengths of **Collaborative Filtering** and **Content-Based Filtering** by learning rich user and item embeddings and using them within scalable Retrieval and Ranking architectures.

Many systems also model the **sequence of user interactions**, allowing them to predict not only *what* a user likes, but also *what they are likely to do next*.

# Additional Notes on Recommendation Systems

## Why the Lowest RMSE Does Not Necessarily Mean the Best Recommendations

A low validation error is only part of the story. In real-world recommendation systems, offline metrics can be misleading.

### There is no perfect ground truth

Unlike standard classification or regression tasks, we never know all of a user's preferences.

A user may love a movie they have never watched, but the dataset contains no evidence of that.

---

### Offline evaluation is limited

A model is trained on historical interactions, but the real question is:

> Will the user click, purchase, or enjoy the recommendation?

This can only be measured in production through online experiments such as A/B testing.

---

### More complex is not always better

The winning solution of the Netflix Prize achieved an impressive improvement in RMSE but was never deployed in production because it was too complex to maintain and scale.

A practical system often beats a theoretically better one.

---

## What Matters Besides Accuracy

### Diversity

Users rarely want ten nearly identical recommendations.

A good recommendation system balances relevance with variety.

![](https://drive.google.com/uc?export=view\&id=1ba9NCWN7V-yTns8AGlDt9BsEF5148t_L)

---

### Freshness

Users often appreciate discovering new content.

Many platforms intentionally promote recently added or trending items instead of relying only on historical popularity.

---

### Trust

Users lose confidence if recommendations constantly feel random.

Trust can be improved through:

* recommendation explanations,
* a balance between familiar and novel content,
* transparent behavior.

---

### Persistence

How long should a recommendation remain visible if the user ignores it?

Removing it too quickly may miss an opportunity, while showing it for too long may become annoying.

---

### Social Context

Signals such as

> "People similar to you liked this"

or

> "Your friends watched this"

can significantly improve recommendations, especially for new users.

---

## Practical Priorities

| Aspect           | Why It Matters                        |
| ---------------- | ------------------------------------- |
| Simplicity       | Easier to build and maintain          |
| Interpretability | Easier to explain and debug           |
| Scalability      | Works on real-world datasets          |
| Maintainability  | Easier for teams to improve over time |

The model should optimize what the business actually values.

Examples:
- Netflix → watch time
- YouTube → watch time
- Spotify → listening time
- Amazon → purchases
- LinkedIn → meaningful interactions

---

## Final Takeaway

The best recommendation system is not necessarily the one with the lowest RMSE.

It is the one that can be deployed, scaled, maintained, and continuously improved while providing value to users.